//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hms_dfis_dev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_location_detail
    {
        public int id { get; set; }
        public Nullable<int> id_building { get; set; }
        public Nullable<int> id_location { get; set; }
        public string name { get; set; }
        public string object_data { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual tm_location tm_location { get; set; }
    }
}
