IF OBJECT_ID('[dbo].[ADSI_User]', 'U') IS NOT NULL DROP TABLE [dbo].[ADSI_User]; 

CREATE TABLE [dbo].[ADSI_User]
(
	[ID] VARCHAR(255) NULL,
	[FULL_NAME] VARCHAR(255) NULL,
	[EMAIL] VARCHAR(255) NULL,
	[INTERNAL_EMAIL] VARCHAR(255) NULL,
	[PHONE] VARCHAR(255) NULL,
	[CREATED_BY] VARCHAR(255) NULL,
	[UPDATED_BY] VARCHAR(255) NULL,
	[LAST_UPDATE] DATETIME NULL
);