IF OBJECT_ID('[dbo].[vNOTES_DATA_FLOW]', 'U') IS NOT NULL DROP TABLE [dbo].[vNOTES_DATA_FLOW]; 

CREATE TABLE [dbo].[vNOTES_DATA_FLOW]
(
	[ID] VARCHAR(255) NULL,
	[NAME] VARCHAR(255) NULL,
	[INITIAL] VARCHAR(255) NULL,
	[TITLE_ID] VARCHAR(255) NULL,
	[TITLE_NAME] VARCHAR(255) NULL,
	[BUSINESS_DOMAIN] VARCHAR(255) NULL,
	[BUSINESS_UNIT] VARCHAR(255) NULL,
	[DIRECTORATE] VARCHAR(255) NULL,
	[DIVISION_P] VARCHAR(255) NULL,
	[DIVISION_Q] VARCHAR(255) NULL,
	[DEPARTMENT] VARCHAR(255) NULL,
	[LOCATION] VARCHAR(255) NULL,
	[CITY] VARCHAR(255) NULL,
	[SPV_ID_STRUCTURE] VARCHAR(255) NULL,
	[SPV_ID_FUNCTIONAL] VARCHAR(255) NULL,
	[SPV_NAME] VARCHAR(255) NULL,
	[SPV_TITLE_ID] VARCHAR(255) NULL,
	[SPV_TITLE] VARCHAR(255) NULL,
	[CONTACT_ADDRESS] VARCHAR(255) NULL,
	[CONTACT_CITY] VARCHAR(255) NULL,
	[COMPANY] VARCHAR(255) NULL,
	[ELIGIBILITY_RANGE] VARCHAR(255) NULL,
	[PHONE] VARCHAR(255) NULL
);