/****** Object:  Table [dbo].[MasterMappingLocation]    Script Date: 25/09/2018 11:58:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterMappingLocation](
	[IDLocation] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDLocation] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


