/* Created By : Fadiyah
Date : 2018-09-28 */

INSERT INTO MasterRole VALUES('ADMIN WAREHOUSE',1,'system',GETDATE(),'system',GETDATE(),'');
INSERT INTO MasterRole VALUES('ADMIN WAREHOUSE TRANSPORT',1,'system',GETDATE(),'system',GETDATE(),'');
INSERT INTO MasterRole VALUES('ADMIN PLANNING TRANSPORT',1,'system',GETDATE(),'system',GETDATE(),'');
INSERT INTO MasterRole VALUES('ADMIN OPERATION TRANSPORT',1,'system',GETDATE(),'system',GETDATE(),'');
INSERT INTO MasterRole VALUES('CUSTOMER',1,'system',GETDATE(),'system',GETDATE(),'');
