USE [TOM]
GO

/****** Object:  Index [uSTO]    Script Date: 27/11/2018 14.03.09 ******/
IF EXISTS(SELECT
    * 
    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
    WHERE CONSTRAINT_NAME ='[uSTO]')
ALTER TABLE [dbo].[TransportOrder] DROP CONSTRAINT [uSTO] 
GO

CREATE UNIQUE NONCLUSTERED INDEX [uSTO]
ON [dbo].[TransportOrder]([STONo])
WHERE [STONo] IS NOT NULL;
GO


