//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPDetail_temp
    {
        public string GPNo { get; set; }
        public string SJNo { get; set; }
        public string Brand { get; set; }
        public Nullable<System.DateTime> SJDate { get; set; }
        public string STONo { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ItemType { get; set; }
        public string Comodity { get; set; }
        public Nullable<System.DateTime> PickIn { get; set; }
        public Nullable<System.DateTime> LoadStart { get; set; }
        public Nullable<System.DateTime> LoadFinish { get; set; }
        public Nullable<System.DateTime> PickOut { get; set; }
        public Nullable<System.DateTime> DropIn { get; set; }
        public Nullable<System.DateTime> UnloadStart { get; set; }
        public Nullable<System.DateTime> UnloadFinish { get; set; }
        public Nullable<System.DateTime> DropOut { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
