//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPHeader
    {
        public string GPNo { get; set; }
        public Nullable<System.DateTime> GPDate { get; set; }
        public string GPStatus { get; set; }
        public string PoliceNumber { get; set; }
        public string FleetType { get; set; }
        public string VendorName { get; set; }
        public string Mode { get; set; }
        public string StartAddress { get; set; }
        public string FinishAddress { get; set; }
        public string Vessel { get; set; }
        public string ShipmentType { get; set; }
        public string ContainerNo { get; set; }
        public string RibbonNo { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
