//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRD_EMP_V2
    {
        public int Row_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public string TITLE_NAME { get; set; }
        public string EMAIL { get; set; }
        public string DIVISION_Q { get; set; }
        public string LOCATION { get; set; }
    }
}
