//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingUnloadingExportView
    {
        public long Row { get; set; }
        public string TransportNo { get; set; }
        public string STONo { get; set; }
        public System.DateTime TransportDate { get; set; }
        public string SenderIDLocation { get; set; }
        public string SenderLocationName { get; set; }
        public string ReceiverIDLocation { get; set; }
        public string ReceiverLocationName { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UoM { get; set; }
        public Nullable<System.DateTime> LoadStartTime { get; set; }
        public Nullable<System.DateTime> LoadFinishTime { get; set; }
        public Nullable<System.DateTime> UnloadStartTime { get; set; }
        public Nullable<System.DateTime> UnloadFinishTime { get; set; }
        public Nullable<decimal> LoadBoxperWorkingTime { get; set; }
        public Nullable<decimal> UnloadBoxperWorkingTime { get; set; }
    }
}
