//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterKilometer
    {
        public int IDMasterKilometer { get; set; }
        public string IDLocationFrom { get; set; }
        public string LocationFrom { get; set; }
        public string LongitudeFrom { get; set; }
        public string LatitudeFrom { get; set; }
        public string LocationTo { get; set; }
        public string IDLocationTo { get; set; }
        public string LongitudeTo { get; set; }
        public string LatitudeTo { get; set; }
        public int Kilometer { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    }
}
