//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterVendor()
        {
            this.MasterServicePoes = new HashSet<MasterServicePo>();
            this.MasterVendor1 = new HashSet<MasterVendor>();
            this.MasterLeadTimes = new HashSet<MasterLeadTime>();
            this.MasterCosts = new HashSet<MasterCost>();
            this.MasterVendorSuggestions = new HashSet<MasterVendorSuggestion>();
            this.TransportDriverManagements = new HashSet<TransportDriverManagement>();
            this.TransportExecutions = new HashSet<TransportExecution>();
        }
    
        public int IDVendor { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> ParentVendor { get; set; }
        public string VendorAddress { get; set; }
        public string VendorRegion { get; set; }
        public string VendorEmail { get; set; }
        public string CC { get; set; }
        public string VendorCategory { get; set; }
        public string TransportationMode { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string VendorProvince { get; set; }
        public string VendorCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterServicePo> MasterServicePoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterVendor> MasterVendor1 { get; set; }
        public virtual MasterVendor MasterVendor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterLeadTime> MasterLeadTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterCost> MasterCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterVendorSuggestion> MasterVendorSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportDriverManagement> TransportDriverManagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportExecution> TransportExecutions { get; set; }
    }
}
