//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterUserLocationMapTreeListView
    {
        public string IDZone { get; set; }
        public string NameZone { get; set; }
        public string IDRegion { get; set; }
        public string NameRegion { get; set; }
        public string IDWarehouse { get; set; }
        public string NameWarehouse { get; set; }
    }
}
