//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDistance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterDistance()
        {
            this.TransportExecutions = new HashSet<TransportExecution>();
            this.TransportExecutions1 = new HashSet<TransportExecution>();
        }
    
        public int IDDistance { get; set; }
        public string DistanceType { get; set; }
        public string IDSender { get; set; }
        public string IDReceiver { get; set; }
        public string TransportationMode { get; set; }
        public decimal Distance { get; set; }
        public int Buffer { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Through { get; set; }
        public string Via { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public System.DateTime EffectiveEndDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual MasterMappingLocation MasterMappingLocation { get; set; }
        public virtual MasterMappingLocation MasterMappingLocation1 { get; set; }
        public virtual MasterMappingLocation MasterMappingLocation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportExecution> TransportExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportExecution> TransportExecutions1 { get; set; }
    }
}
