//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterCost()
        {
            this.TransportExecutions = new HashSet<TransportExecution>();
        }
    
        public int IDCost { get; set; }
        public string CostType { get; set; }
        public int IDVendor { get; set; }
        public string VehicleType { get; set; }
        public string OrderType { get; set; }
        public string SenderIDLocation { get; set; }
        public string ThroughIDLocation { get; set; }
        public string ReceiverIDLocation { get; set; }
        public string Via { get; set; }
        public Nullable<decimal> MinimumKM { get; set; }
        public Nullable<int> MinimumBox { get; set; }
        public decimal BasedPrice { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> AdditionalUnitPrice { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public System.DateTime EffectiveEndDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual MasterVendor MasterVendor { get; set; }
        public virtual MasterMappingLocation MasterMappingLocation { get; set; }
        public virtual MasterMappingLocation MasterMappingLocation1 { get; set; }
        public virtual MasterMappingLocation MasterMappingLocation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportExecution> TransportExecutions { get; set; }
    }
}
