//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServicePo
    {
        public int IDServicePO { get; set; }
        public int IDVendor { get; set; }
        public string ServicePONumber { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public System.DateTime EffectiveEndDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual MasterVendor MasterVendor { get; set; }
    }
}
