//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Threading.Tasks;


    public class User
    {
        // Kolom di DB: [ID], jadi mappingkan properti ke kolomnya
        public string ID { get; set; }  // berisi "DOMAIN\sam"

        public string Name { get; set; }

        public string Email { get; set; }
    }





    public partial class TOMContextDB : DbContext
    {
        public TOMContextDB()
            : base("name=TOMContextDB")
        {
        }



        public virtual DbSet<User> Users { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {



            // If you’re using custom tables:
            modelBuilder.Entity<User>().ToTable("Users");
            modelBuilder.Entity<MasterUser>().ToTable("MasterUsers");
            // Define keys if not by convention
            modelBuilder.Entity<User>().HasKey(u => u.ID);
            modelBuilder.Entity<MasterUser>().HasKey(m => m.IDUser);

            throw new UnintentionalCodeFirstException();
        }


    
        public virtual DbSet<MasterConfiguration> MasterConfigurations { get; set; }
        public virtual DbSet<MasterConfigurationEmail> MasterConfigurationEmails { get; set; }
        public virtual DbSet<MasterFunction> MasterFunctions { get; set; }

        public virtual DbSet<MasterGenWeek> MasterGenWeeks { get; set; }
        public virtual DbSet<MasterIMDLRole> MasterIMDLRoles { get; set; }
        public virtual DbSet<MasterList> MasterLists { get; set; }
        public virtual DbSet<MasterMapping> MasterMappings { get; set; }
        public virtual DbSet<MasterRole> MasterRoles { get; set; }
        public virtual DbSet<MasterRolesFunctionMapping> MasterRolesFunctionMappings { get; set; }
        public virtual DbSet<MasterServicePo> MasterServicePoes { get; set; }
        public virtual DbSet<MasterTruckSealStock> MasterTruckSealStocks { get; set; }
        public virtual DbSet<MasterUom> MasterUoms { get; set; }
        public virtual DbSet<MasterUser> MasterUsers { get; set; }

        //public virtual DbSet<MasterUserLocationMapping> MasterUserLocationMappings { get; set; }
        public virtual DbSet<MasterUserRoleDelegation> MasterUserRoleDelegations { get; set; }
        public virtual DbSet<MasterUserRoleMapping> MasterUserRoleMappings { get; set; }
        public virtual DbSet<MasterVendor> MasterVendors { get; set; }
        public virtual DbSet<NotificationSystem> NotificationSystems { get; set; }
        public virtual DbSet<SchemaVersion> SchemaVersions { get; set; }
        public virtual DbSet<TransportExecutionStatusLog> TransportExecutionStatusLogs { get; set; }
        public virtual DbSet<TransportTruckArrival> TransportTruckArrivals { get; set; }
        public virtual DbSet<TruckArrivalHistory> TruckArrivalHistories { get; set; }
        public virtual DbSet<TruckArrivalTemp> TruckArrivalTemps { get; set; }
        public virtual DbSet<MasterCostLatestEffectiveDateDataView> MasterCostLatestEffectiveDateDataViews { get; set; }
        public virtual DbSet<TransportOrderChangeLog> TransportOrderChangeLogs { get; set; }
        public virtual DbSet<TransportOrderDetail> TransportOrderDetails { get; set; }
        public virtual DbSet<TransportOrderDetailChangeLog> TransportOrderDetailChangeLogs { get; set; }
        public virtual DbSet<CustomReportState> CustomReportStates { get; set; }
        public virtual DbSet<MasterCostCenter> MasterCostCenters { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
        public virtual DbSet<MasterRoleFunctionTreeListView> MasterRoleFunctionTreeListViews { get; set; }
        public virtual DbSet<MasterUserRoleDelegationView> MasterUserRoleDelegationViews { get; set; }
        public virtual DbSet<UserRolesSecurityView> UserRolesSecurityViews { get; set; }
        public virtual DbSet<MasterUserLocationMapTreeListView> MasterUserLocationMapTreeListViews { get; set; }
        public virtual DbSet<MasterIMDLRoleLocation> MasterIMDLRoleLocations { get; set; }
        public virtual DbSet<MasterUserLocationMapping> MasterUserLocationMappings { get; set; }
        public virtual DbSet<UserLocationDelegation> UserLocationDelegations { get; set; }
        public virtual DbSet<MasterDistance> MasterDistances { get; set; }
        public virtual DbSet<MasterLeadTime> MasterLeadTimes { get; set; }
        public virtual DbSet<MasterCost> MasterCosts { get; set; }
        public virtual DbSet<MasterVendorSuggestion> MasterVendorSuggestions { get; set; }
        public virtual DbSet<TransportSeal> TransportSeals { get; set; }
        public virtual DbSet<MasterKilometer> MasterKilometers { get; set; }
        public virtual DbSet<MasterMappingLocation> MasterMappingLocations { get; set; }
        public virtual DbSet<MasterTransportRegion> MasterTransportRegions { get; set; }
        public virtual DbSet<HRD_EMP_V2> HRD_EMP_V2 { get; set; }
        public virtual DbSet<MasterLocation> MasterLocations { get; set; }
        public virtual DbSet<TransportOrderRequest> TransportOrderRequests { get; set; }
        public virtual DbSet<TransportPickingListLog> TransportPickingListLogs { get; set; }
        public virtual DbSet<TransportVendorChangeLog> TransportVendorChangeLogs { get; set; }
        public virtual DbSet<TransportPositionDetail> TransportPositionDetails { get; set; }
        public virtual DbSet<TransportMonitoringView> TransportMonitoringViews { get; set; }
        public virtual DbSet<GeneralBuildingFacility> GeneralBuildingFacilities { get; set; }
        public virtual DbSet<GPDetail> GPDetails { get; set; }
        public virtual DbSet<GPDetail_temp> GPDetail_temp { get; set; }
        public virtual DbSet<GPHeader> GPHeaders { get; set; }
        public virtual DbSet<GPHeader_temp> GPHeader_temp { get; set; }
        public virtual DbSet<TransportLostClaimFACode> TransportLostClaimFACodes { get; set; }
        public virtual DbSet<TransportLostClaimUploadBox> TransportLostClaimUploadBoxes { get; set; }
        public virtual DbSet<TransportOrderRequestSummary> TransportOrderRequestSummaries { get; set; }
        public virtual DbSet<TransportRoute> TransportRoutes { get; set; }
        public virtual DbSet<TransportTicketNCR> TransportTicketNCRs { get; set; }
        public virtual DbSet<TransportSummaryReclassView> TransportSummaryReclassViews { get; set; }
        public virtual DbSet<TransportOrderRequestHeader> TransportOrderRequestHeaders { get; set; }
        public virtual DbSet<TransportDriverManagement> TransportDriverManagements { get; set; }
        public virtual DbSet<LoadingUnloadingExportView> LoadingUnloadingExportViews { get; set; }
        public virtual DbSet<TransportMonitoringTruckTrainList> TransportMonitoringTruckTrainLists { get; set; }
        public virtual DbSet<TransportVehicleData> TransportVehicleDatas { get; set; }
        public virtual DbSet<TransportOrder> TransportOrders { get; set; }
        public virtual DbSet<MasterFABrand> MasterFABrands { get; set; }
        public virtual DbSet<TransportVesselMonitoring> TransportVesselMonitorings { get; set; }
        public virtual DbSet<TransportExecutionTemp> TransportExecutionTemps { get; set; }
        public virtual DbSet<MasterLoadFactorCFP> MasterLoadFactorCFPs { get; set; }
        public virtual DbSet<TransportLostClaimDamage> TransportLostClaimDamages { get; set; }
        public virtual DbSet<TransportExecution> TransportExecutions { get; set; }
        public virtual DbSet<TransportPickingListView> TransportPickingListViews { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_alterdiagram1(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram1", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram1(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram1", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition1_Result> sp_helpdiagramdefinition1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition1_Result>("sp_helpdiagramdefinition1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams1_Result> sp_helpdiagrams1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams1_Result>("sp_helpdiagrams1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram1(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram1", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams1");
        }
    
        public virtual int sp_alterdiagram2(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram2", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram2(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram2", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram2(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram2", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition2_Result> sp_helpdiagramdefinition2(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition2_Result>("sp_helpdiagramdefinition2", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams2_Result> sp_helpdiagrams2(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams2_Result>("sp_helpdiagrams2", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram2(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram2", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams2");
        }
    
        [DbFunction("TOMContextDB", "CheckSNTruckSeal")]
        public virtual IQueryable<CheckSNTruckSeal_Result> CheckSNTruckSeal(Nullable<int> snfrom, Nullable<int> snto)
        {
            var snfromParameter = snfrom.HasValue ?
                new ObjectParameter("snfrom", snfrom) :
                new ObjectParameter("snfrom", typeof(int));
    
            var sntoParameter = snto.HasValue ?
                new ObjectParameter("snto", snto) :
                new ObjectParameter("snto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CheckSNTruckSeal_Result>("[TOMContextDB].[CheckSNTruckSeal](@snfrom, @snto)", snfromParameter, sntoParameter);
        }
    
        public virtual int GenTransportUnitFreq(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenTransportUnitFreq", dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int sp_alterdiagram3(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram3", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram3(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram3", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram3(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram3", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition3_Result> sp_helpdiagramdefinition3(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition3_Result>("sp_helpdiagramdefinition3", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams3_Result> sp_helpdiagrams3(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams3_Result>("sp_helpdiagrams3", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram3(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram3", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams3");
        }
    
        public virtual int SendEmailTransportExecutionSI(string mail, string nama, string reg, string week, string tglawal, string tglakhir, string sender, string files)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var namaParameter = nama != null ?
                new ObjectParameter("nama", nama) :
                new ObjectParameter("nama", typeof(string));
    
            var regParameter = reg != null ?
                new ObjectParameter("reg", reg) :
                new ObjectParameter("reg", typeof(string));
    
            var weekParameter = week != null ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(string));
    
            var tglawalParameter = tglawal != null ?
                new ObjectParameter("tglawal", tglawal) :
                new ObjectParameter("tglawal", typeof(string));
    
            var tglakhirParameter = tglakhir != null ?
                new ObjectParameter("tglakhir", tglakhir) :
                new ObjectParameter("tglakhir", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var filesParameter = files != null ?
                new ObjectParameter("files", files) :
                new ObjectParameter("files", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SendEmailTransportExecutionSI", mailParameter, namaParameter, regParameter, weekParameter, tglawalParameter, tglakhirParameter, senderParameter, filesParameter);
        }
    
        [DbFunction("TOMContextDB", "FnTransportationSummary")]
        public virtual IQueryable<FnTransportationSummary_Result> FnTransportationSummary(string filterTab, string filterRole, string filterSort, string filteryear)
        {
            var filterTabParameter = filterTab != null ?
                new ObjectParameter("filterTab", filterTab) :
                new ObjectParameter("filterTab", typeof(string));
    
            var filterRoleParameter = filterRole != null ?
                new ObjectParameter("filterRole", filterRole) :
                new ObjectParameter("filterRole", typeof(string));
    
            var filterSortParameter = filterSort != null ?
                new ObjectParameter("filterSort", filterSort) :
                new ObjectParameter("filterSort", typeof(string));
    
            var filteryearParameter = filteryear != null ?
                new ObjectParameter("filteryear", filteryear) :
                new ObjectParameter("filteryear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FnTransportationSummary_Result>("[TOMContextDB].[FnTransportationSummary](@filterTab, @filterRole, @filterSort, @filteryear)", filterTabParameter, filterRoleParameter, filterSortParameter, filteryearParameter);
        }
    
        [DbFunction("TOMContextDB", "KPILoadFactorAvg")]
        public virtual IQueryable<KPILoadFactorAvg_Result> KPILoadFactorAvg(Nullable<int> filterYear)
        {
            var filterYearParameter = filterYear.HasValue ?
                new ObjectParameter("filterYear", filterYear) :
                new ObjectParameter("filterYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<KPILoadFactorAvg_Result>("[TOMContextDB].[KPILoadFactorAvg](@filterYear)", filterYearParameter);
        }
    
        public virtual int CalculateLoadFactorCFP(Nullable<int> idTranExeParam)
        {
            var idTranExeParamParameter = idTranExeParam.HasValue ?
                new ObjectParameter("idTranExeParam", idTranExeParam) :
                new ObjectParameter("idTranExeParam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalculateLoadFactorCFP", idTranExeParamParameter);
        }
    
        [DbFunction("TOMContextDB", "FnTransportationSummaryCRate")]
        public virtual IQueryable<FnTransportationSummaryCRate_Result> FnTransportationSummaryCRate(string filteryear)
        {
            var filteryearParameter = filteryear != null ?
                new ObjectParameter("filteryear", filteryear) :
                new ObjectParameter("filteryear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FnTransportationSummaryCRate_Result>("[TOMContextDB].[FnTransportationSummaryCRate](@filteryear)", filteryearParameter);
        }
    
        [DbFunction("TOMContextDB", "FN_TRANSPORT_EXECUTION_LIST_ADD")]
        public virtual IQueryable<FN_TRANSPORT_EXECUTION_LIST_ADD_Result> FN_TRANSPORT_EXECUTION_LIST_ADD(string executionTypeFilter, string zoneFilter, string orderTypeFilter, Nullable<int> weekFilter, string senderFilter, string vehicleTypeFilter, Nullable<int> yearFilter)
        {
            var executionTypeFilterParameter = executionTypeFilter != null ?
                new ObjectParameter("executionTypeFilter", executionTypeFilter) :
                new ObjectParameter("executionTypeFilter", typeof(string));
    
            var zoneFilterParameter = zoneFilter != null ?
                new ObjectParameter("zoneFilter", zoneFilter) :
                new ObjectParameter("zoneFilter", typeof(string));
    
            var orderTypeFilterParameter = orderTypeFilter != null ?
                new ObjectParameter("orderTypeFilter", orderTypeFilter) :
                new ObjectParameter("orderTypeFilter", typeof(string));
    
            var weekFilterParameter = weekFilter.HasValue ?
                new ObjectParameter("weekFilter", weekFilter) :
                new ObjectParameter("weekFilter", typeof(int));
    
            var senderFilterParameter = senderFilter != null ?
                new ObjectParameter("senderFilter", senderFilter) :
                new ObjectParameter("senderFilter", typeof(string));
    
            var vehicleTypeFilterParameter = vehicleTypeFilter != null ?
                new ObjectParameter("vehicleTypeFilter", vehicleTypeFilter) :
                new ObjectParameter("vehicleTypeFilter", typeof(string));
    
            var yearFilterParameter = yearFilter.HasValue ?
                new ObjectParameter("yearFilter", yearFilter) :
                new ObjectParameter("yearFilter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_TRANSPORT_EXECUTION_LIST_ADD_Result>("[TOMContextDB].[FN_TRANSPORT_EXECUTION_LIST_ADD](@executionTypeFilter, @zoneFilter, @orderTypeFilter, @weekFilter, @senderFilter, @vehicleTypeFilter, @yearFilter)", executionTypeFilterParameter, zoneFilterParameter, orderTypeFilterParameter, weekFilterParameter, senderFilterParameter, vehicleTypeFilterParameter, yearFilterParameter);
        }
    
        public virtual int spSendEmail(string profile_name, string recipients, string copy_recipients, string body, string body_format, string subject, string file_attachments)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var body_formatParameter = body_format != null ?
                new ObjectParameter("body_format", body_format) :
                new ObjectParameter("body_format", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var file_attachmentsParameter = file_attachments != null ?
                new ObjectParameter("file_attachments", file_attachments) :
                new ObjectParameter("file_attachments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSendEmail", profile_nameParameter, recipientsParameter, copy_recipientsParameter, bodyParameter, body_formatParameter, subjectParameter, file_attachmentsParameter);
        }
    
        public virtual int InsertOrUpdateMstLocation(string iDLocation, string locationName, string parentLocation, string type, Nullable<bool> isActive, string remarks, string user)
        {
            var iDLocationParameter = iDLocation != null ?
                new ObjectParameter("IDLocation", iDLocation) :
                new ObjectParameter("IDLocation", typeof(string));
    
            var locationNameParameter = locationName != null ?
                new ObjectParameter("LocationName", locationName) :
                new ObjectParameter("LocationName", typeof(string));
    
            var parentLocationParameter = parentLocation != null ?
                new ObjectParameter("ParentLocation", parentLocation) :
                new ObjectParameter("ParentLocation", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOrUpdateMstLocation", iDLocationParameter, locationNameParameter, parentLocationParameter, typeParameter, isActiveParameter, remarksParameter, userParameter);
        }
    
        public virtual ObjectResult<SP_GetTransportOrderRequest_Result> SP_GetTransportOrderRequest(string oNFilter, string zoneFilter, string oTFilter, string oVFilter, Nullable<System.DateTime> shipDateBeginFilter, Nullable<System.DateTime> shipDateEndFilter, string mTFilter, string statusFilter, string senderFilter, string receiverFilter, string creatorFilter, string locationFilter, Nullable<byte> allAccess)
        {
            var oNFilterParameter = oNFilter != null ?
                new ObjectParameter("ONFilter", oNFilter) :
                new ObjectParameter("ONFilter", typeof(string));
    
            var zoneFilterParameter = zoneFilter != null ?
                new ObjectParameter("ZoneFilter", zoneFilter) :
                new ObjectParameter("ZoneFilter", typeof(string));
    
            var oTFilterParameter = oTFilter != null ?
                new ObjectParameter("OTFilter", oTFilter) :
                new ObjectParameter("OTFilter", typeof(string));
    
            var oVFilterParameter = oVFilter != null ?
                new ObjectParameter("OVFilter", oVFilter) :
                new ObjectParameter("OVFilter", typeof(string));
    
            var shipDateBeginFilterParameter = shipDateBeginFilter.HasValue ?
                new ObjectParameter("ShipDateBeginFilter", shipDateBeginFilter) :
                new ObjectParameter("ShipDateBeginFilter", typeof(System.DateTime));
    
            var shipDateEndFilterParameter = shipDateEndFilter.HasValue ?
                new ObjectParameter("ShipDateEndFilter", shipDateEndFilter) :
                new ObjectParameter("ShipDateEndFilter", typeof(System.DateTime));
    
            var mTFilterParameter = mTFilter != null ?
                new ObjectParameter("MTFilter", mTFilter) :
                new ObjectParameter("MTFilter", typeof(string));
    
            var statusFilterParameter = statusFilter != null ?
                new ObjectParameter("StatusFilter", statusFilter) :
                new ObjectParameter("StatusFilter", typeof(string));
    
            var senderFilterParameter = senderFilter != null ?
                new ObjectParameter("SenderFilter", senderFilter) :
                new ObjectParameter("SenderFilter", typeof(string));
    
            var receiverFilterParameter = receiverFilter != null ?
                new ObjectParameter("ReceiverFilter", receiverFilter) :
                new ObjectParameter("ReceiverFilter", typeof(string));
    
            var creatorFilterParameter = creatorFilter != null ?
                new ObjectParameter("CreatorFilter", creatorFilter) :
                new ObjectParameter("CreatorFilter", typeof(string));
    
            var locationFilterParameter = locationFilter != null ?
                new ObjectParameter("LocationFilter", locationFilter) :
                new ObjectParameter("LocationFilter", typeof(string));
    
            var allAccessParameter = allAccess.HasValue ?
                new ObjectParameter("AllAccess", allAccess) :
                new ObjectParameter("AllAccess", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTransportOrderRequest_Result>("SP_GetTransportOrderRequest", oNFilterParameter, zoneFilterParameter, oTFilterParameter, oVFilterParameter, shipDateBeginFilterParameter, shipDateEndFilterParameter, mTFilterParameter, statusFilterParameter, senderFilterParameter, receiverFilterParameter, creatorFilterParameter, locationFilterParameter, allAccessParameter);
        }
    
        public virtual int CalculateCost(string idTranExeParam, string idUserParam, Nullable<int> recalculate)
        {
            var idTranExeParamParameter = idTranExeParam != null ?
                new ObjectParameter("idTranExeParam", idTranExeParam) :
                new ObjectParameter("idTranExeParam", typeof(string));
    
            var idUserParamParameter = idUserParam != null ?
                new ObjectParameter("idUserParam", idUserParam) :
                new ObjectParameter("idUserParam", typeof(string));
    
            var recalculateParameter = recalculate.HasValue ?
                new ObjectParameter("recalculate", recalculate) :
                new ObjectParameter("recalculate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalculateCost", idTranExeParamParameter, idUserParamParameter, recalculateParameter);
        }
    
        public virtual int SendEmailPickingList(string sendEmailBy)
        {
            var sendEmailByParameter = sendEmailBy != null ?
                new ObjectParameter("sendEmailBy", sendEmailBy) :
                new ObjectParameter("sendEmailBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SendEmailPickingList", sendEmailByParameter);
        }

       
    }
}
