//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportSeal
    {
        public int IDTransportSeal { get; set; }
        public int IDTransportExecution { get; set; }
        public string SealNumber { get; set; }
        public string SealActivity { get; set; }
        public string IDLocation { get; set; }
        public System.DateTime SealTime { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual TransportExecution TransportExecution { get; set; }
    }
}
