//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportMonitoringTruckTrainList
    {
        public Nullable<int> IDTransportExecution { get; set; }
        public Nullable<int> IDTransportOrder { get; set; }
        public string TransportNo { get; set; }
        public string TransportStatus { get; set; }
        public Nullable<System.DateTime> TransportDate { get; set; }
        public string TransportMode { get; set; }
        public string STONo { get; set; }
        public Nullable<int> IDVendor { get; set; }
        public string SenderIDLocation { get; set; }
        public string ReceiverIDLocation { get; set; }
        public string IDStartLocation { get; set; }
        public string IDFinishLocation { get; set; }
        public string VehicleType { get; set; }
        public string PoliceRegNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Driver1 { get; set; }
        public string Driver2 { get; set; }
        public string CoDriver { get; set; }
        public string VendorName { get; set; }
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
        public string StartName { get; set; }
        public string FinishName { get; set; }
    }
}
