//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportExecution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportExecution()
        {
            this.TransportOrders = new HashSet<TransportOrder>();
            this.TransportExecutionStatusLogs = new HashSet<TransportExecutionStatusLog>();
            this.TransportSeals = new HashSet<TransportSeal>();
            this.TransportVendorChangeLogs = new HashSet<TransportVendorChangeLog>();
            this.TransportPositionDetails = new HashSet<TransportPositionDetail>();
            this.TransportRoutes = new HashSet<TransportRoute>();
            this.TransportVesselMonitorings = new HashSet<TransportVesselMonitoring>();
        }
    
        public int IDTransportExecution { get; set; }
        public string TransportNo { get; set; }
        public string TransportStatus { get; set; }
        public System.DateTime TransportDate { get; set; }
        public string TransportCategory { get; set; }
        public string ActualVehicleType { get; set; }
        public string TransportMode { get; set; }
        public Nullable<int> IDVendor { get; set; }
        public string SIType { get; set; }
        public string SIStatus { get; set; }
        public Nullable<byte> SIWeek { get; set; }
        public Nullable<System.DateTime> TargetOfArrival { get; set; }
        public Nullable<System.DateTime> ActualArrive { get; set; }
        public string StartLocation { get; set; }
        public string FinishLocation { get; set; }
        public string ServicePONo { get; set; }
        public string ActualCostCenter { get; set; }
        public string PoliceRegNo { get; set; }
        public string IDDriver1 { get; set; }
        public string IDDriver2 { get; set; }
        public string IDCoDriver { get; set; }
        public Nullable<int> IDDistanceKMBased { get; set; }
        public Nullable<int> IDDistanceBoxTripBased { get; set; }
        public Nullable<int> IDCost { get; set; }
        public Nullable<decimal> TotalKM { get; set; }
        public Nullable<int> TotalBox { get; set; }
        public Nullable<decimal> ASDPCost { get; set; }
        public Nullable<decimal> SPSICost { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public string Via { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string ServiceGRNo { get; set; }
        public Nullable<int> DeliveryQty { get; set; }
        public Nullable<decimal> CFPLiter { get; set; }
        public Nullable<decimal> CFPTKM { get; set; }
        public Nullable<decimal> KGCO2 { get; set; }
        public Nullable<decimal> AVGLoadFactor { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalKMRail { get; set; }
        public Nullable<decimal> TotalKMBased { get; set; }
        public Nullable<decimal> TotalKMSea { get; set; }
        public Nullable<decimal> BasedCost { get; set; }
        public Nullable<decimal> DiscountCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> IDCostCenter { get; set; }
    
        public virtual MasterCost MasterCost { get; set; }
        public virtual MasterCostCenter MasterCostCenter { get; set; }
        public virtual MasterDistance MasterDistance { get; set; }
        public virtual MasterDistance MasterDistance1 { get; set; }
        public virtual MasterVendor MasterVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportOrder> TransportOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportExecutionStatusLog> TransportExecutionStatusLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportSeal> TransportSeals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportVendorChangeLog> TransportVendorChangeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportPositionDetail> TransportPositionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportRoute> TransportRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportVesselMonitoring> TransportVesselMonitorings { get; set; }
    }
}
