//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrderRequestSummary
    {
        public int IDRequest { get; set; }
        public string RequestNo { get; set; }
        public string Zone { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public bool IsActive { get; set; }
        public int IDTransportOrder { get; set; }
        public int IDTransportOrderDetail { get; set; }
        public string SenderIDLocation { get; set; }
        public string ReceiverIDLocation { get; set; }
        public string OrderStatus { get; set; }
        public string OrderType { get; set; }
        public string VehicleType { get; set; }
        public string STONo { get; set; }
        public string MaterialType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool OrderIsActive { get; set; }
    }
}
