//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportLostClaimDamage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportLostClaimDamage()
        {
            this.TransportLostClaimFACodes = new HashSet<TransportLostClaimFACode>();
            this.TransportLostClaimUploadBoxes = new HashSet<TransportLostClaimUploadBox>();
        }
    
        public string GPNumber { get; set; }
        public string SJNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SJDate { get; set; }
        public string ClaimType { get; set; }
        public string DeliveryNumberNote { get; set; }
        public string OriginWarehouse { get; set; }
        public string DestinationWarehouse { get; set; }
        public string STONumber { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public Nullable<System.DateTime> DateOfIncident { get; set; }
        public Nullable<int> TransportationVendor { get; set; }
        public string PoliceRegNumber { get; set; }
        public string Driver { get; set; }
        public string CoDriver { get; set; }
        public string Receiver { get; set; }
        public string Witness { get; set; }
        public string DNtoReverseLogistics { get; set; }
        public string Attachment { get; set; }
        public string ClaimExpense { get; set; }
        public string TransportationMode { get; set; }
        public string GoodsCategory { get; set; }
        public Nullable<decimal> InitClaimedAmount { get; set; }
        public string ClaimCategory { get; set; }
        public Nullable<int> TotalClaimInPack { get; set; }
        public Nullable<int> TotalClaimInStick { get; set; }
        public Nullable<System.DateTime> BSWarehouseReceiveDate { get; set; }
        public string HMSMemoNumber { get; set; }
        public Nullable<System.DateTime> HMSMemoDate { get; set; }
        public string HMSMemoFile { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<System.DateTime> VendorPaymentDate { get; set; }
        public Nullable<decimal> GrossLossAmount { get; set; }
        public Nullable<decimal> NetClaim { get; set; }
        public string InsurancePaymentProof { get; set; }
        public string EDPSNumber { get; set; }
        public Nullable<System.DateTime> EDPSDate { get; set; }
        public Nullable<System.DateTime> IncinerationReportDate { get; set; }
        public string IncinerationReportFile { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string Supervisor { get; set; }
        public string RealStatus { get; set; }
        public string Driver2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportLostClaimFACode> TransportLostClaimFACodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportLostClaimUploadBox> TransportLostClaimUploadBoxes { get; set; }
    }
}
