//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportOrderDetail()
        {
            this.TransportOrderDetailChangeLogs = new HashSet<TransportOrderDetailChangeLog>();
        }
    
        public int IDTransportOrderDetail { get; set; }
        public int IDTransportOrder { get; set; }
        public string Supplier { get; set; }
        public string MaterialType { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UoM { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportOrderDetailChangeLog> TransportOrderDetailChangeLogs { get; set; }
        public virtual TransportOrder TransportOrder { get; set; }
    }
}
