//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportVehicleData
    {
        public string IDPoliceRegNumber { get; set; }
        public Nullable<int> ManufacturingYear { get; set; }
        public string Karoseri { get; set; }
        public string Merk { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Cargo { get; set; }
        public string VehicleIdentityNumber { get; set; }
        public string EngineNumber { get; set; }
        public string BaseTown { get; set; }
        public System.DateTime STNKValidityPeriod { get; set; }
        public string GPS { get; set; }
        public string Status { get; set; }
        public string AttachmentSTNK { get; set; }
        public string AttachmentPhoto { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string AttachmentPhotoTwo { get; set; }
        public string AttachmentPhotoThree { get; set; }
        public int IDVendor { get; set; }
    }
}
