//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportOrder()
        {
            this.TransportOrderDetails = new HashSet<TransportOrderDetail>();
            this.TransportOrderChangeLogs = new HashSet<TransportOrderChangeLog>();
        }
    
        public int IDTransportOrder { get; set; }
        public Nullable<int> IDRequest { get; set; }
        public Nullable<int> IDTransportExecution { get; set; }
        public Nullable<int> IDTransportPickingListLog { get; set; }
        public string STONo { get; set; }
        public string DefaultSeqNo { get; set; }
        public string SeqNo { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public Nullable<decimal> KM { get; set; }
        public string SenderIDLocation { get; set; }
        public string ActualSenderIDLocation { get; set; }
        public string ReceiverIDLocation { get; set; }
        public string ActualReceiverIDLocation { get; set; }
        public Nullable<byte> LeadTime { get; set; }
        public string VehicleType { get; set; }
        public string OrderType { get; set; }
        public string CostCenter { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> MaterialReceivedTime { get; set; }
        public Nullable<bool> IsMaterialReceived { get; set; }
        public Nullable<System.DateTime> EstArrivalDate { get; set; }
        public Nullable<System.DateTime> GRDate { get; set; }
        public Nullable<System.DateTime> LoadStartTime { get; set; }
        public Nullable<System.DateTime> LoadFinishTime { get; set; }
        public Nullable<System.DateTime> UnloadStartTime { get; set; }
        public Nullable<System.DateTime> UnloadFinishTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> FlagEmail { get; set; }
        public Nullable<int> IDLeadTime { get; set; }
        public Nullable<int> IDCostCenter { get; set; }
        public string ChangeLogFields { get; set; }
        public string ZoneBased { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<decimal> LoadBoxperWorkingTime { get; set; }
        public Nullable<decimal> UnloadBoxperWorkingTime { get; set; }
        public Nullable<System.DateTime> GIDate { get; set; }
        public string OrderCategory { get; set; }
        public Nullable<int> POWeek { get; set; }
        public Nullable<decimal> TotalKM { get; set; }
        public string GIBy { get; set; }
        public string GRBy { get; set; }
    
        public virtual MasterCostCenter MasterCostCenter { get; set; }
        public virtual TransportOrderRequest TransportOrderRequest { get; set; }
        public virtual TransportPickingListLog TransportPickingListLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportOrderDetail> TransportOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportOrderChangeLog> TransportOrderChangeLogs { get; set; }
        public virtual TransportExecution TransportExecution { get; set; }
    }
}
