//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportTruckArrival
    {
        public int IDTransportTruckArrival { get; set; }
        public string PoliceNumber { get; set; }
        public string GPNo { get; set; }
        public System.DateTime Date { get; set; }
        public string LongitudeDestination { get; set; }
        public string LatitudeDestination { get; set; }
        public string LongitudeTruck { get; set; }
        public string LatitudeTruck { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string ETACategory { get; set; }
        public Nullable<System.DateTime> ETACalculate { get; set; }
        public string ETACategoryCalculate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
