//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrderChangeLog
    {
        public int IDTransportOrderChangeLog { get; set; }
        public int IDTransportOrder { get; set; }
        public Nullable<int> Version { get; set; }
        public string OldValue { get; set; }
        public string ModifiedField { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual TransportOrder TransportOrder { get; set; }
    }
}
