//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportVendorChangeLog
    {
        public int IDVendorChangeLog { get; set; }
        public int IDTransportExecution { get; set; }
        public System.DateTime TransportDate { get; set; }
        public int IDVendor { get; set; }
        public string SIType { get; set; }
        public string SIStatus { get; set; }
        public Nullable<System.DateTime> TargetOfArrival { get; set; }
        public Nullable<System.DateTime> ActualArrive { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual TransportExecution TransportExecution { get; set; }
    }
}
