//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int IDLog { get; set; }
        public int IDFunction { get; set; }
        public string IDUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Action { get; set; }
        public string Remarks { get; set; }
    
        public virtual MasterFunction MasterFunction { get; set; }
        public virtual MasterUser MasterUser { get; set; }
    }
}
