//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportPositionDetail
    {
        public int IDTransportPositionDetail { get; set; }
        public Nullable<int> IDTransportExecution { get; set; }
        public Nullable<System.DateTime> PositionDate { get; set; }
        public string PositionName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual TransportExecution TransportExecution { get; set; }
    }
}
