//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckArrivalHistory
    {
        public int IDTruckArrivalHistory { get; set; }
        public string PoliceNumber { get; set; }
        public string GPNo { get; set; }
        public System.DateTime Date { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string IDLocation { get; set; }
        public string Location { get; set; }
    }
}
