//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckArrivalTemp
    {
        public int IDTruckArrivalTemp { get; set; }
        public string PoliceNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Location { get; set; }
        public int Speed { get; set; }
        public int Satellite { get; set; }
        public string SOS { get; set; }
        public string DoorRear { get; set; }
        public string DoorLeft { get; set; }
        public string DoorRight { get; set; }
        public string Kabupaten { get; set; }
        public string Kecamatan { get; set; }
        public Nullable<int> INTPower { get; set; }
        public Nullable<int> EXTPower { get; set; }
        public string Status { get; set; }
        public string Engine { get; set; }
        public string Fatiqeu { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
