//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolesSecurityView
    {
        public string IDUser { get; set; }
        public string FullName { get; set; }
        public int IDRole { get; set; }
        public string rolename { get; set; }
        public int IDFunction { get; set; }
        public string FunctionName { get; set; }
        public string Type { get; set; }
        public Nullable<int> ParentIDFunction { get; set; }
    }
}
