//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOM.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocationDelegation
    {
        public int IDUserLocationDelegation { get; set; }
        public int IDUserDelegation { get; set; }
        public string DelegationIDLocation { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual MasterUserRoleDelegation MasterUserRoleDelegation { get; set; }
        public virtual MasterMappingLocation MasterMappingLocation { get; set; }
    }
}
